<a href="https://colab.research.google.com/github/priyanshgupta1998/All_codes/blob/master/code_prac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

#linalg.det

In [31]:
a = [[1 , 2], [2, 1]]
print(np.linalg.det(a))  #determinant

-2.9999999999999996


In [5]:
print(np.linalg.det([[7 , 2], [8, 1]]))

-8.999999999999998


#linalg.eig

`The linalg.eig computes the eigenvalues and right eigenvectors of a square array`

In [0]:
vals, vecs = np.linalg.eig([[1 , 2], [2, 1]])

In [8]:
print(vals)
print(vecs)

[ 3. -1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


#linalg.inv



```
The linalg.inv tool computes the (multiplicative) inverse of a matrix.
```



In [10]:
np.linalg.inv([[1 , 2], [2, 1]])

array([[-0.33333333,  0.66666667],
       [ 0.66666667, -0.33333333]])

In [0]:
a=[]
N=2
for row in range(N):
  for column in range(N):
        a[column]= 5

print(a)

In [18]:
def createMatrix(row, col,arr):
    a = []
    for i in range(row):
        b = []
        for j in range(col):
            b.append(arr[row * i + j])
        a.append(b)

    return a

arr = ['a','b','c','d','e','f','h','i','j']
mat = createMatrix(3,3,arr)
mat

[['a', 'b', 'c'], ['d', 'e', 'f'], ['h', 'i', 'j']]

In [0]:
def make_matrix(row,col,arr):
  a=[]
  for i in range(row):
    b=[]
    for j in range(col):
      b.append(arr[j+row*i])
    a.append(b)
  return a

In [25]:
arr = [ 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
res = make_matrix(4,4,arr)
print(res)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [30]:
N = int(input())
a = []
for i in range(N):
  b= []
  for j in range(N):
    k = input()
    b.append(k)
  a.append(b)
  


2
5.6
6.9
8.2
1.2
[['5.6', '6.9'], ['8.2', '1.2']]


In [33]:
import numpy as np
N = int(input())
a = []
for i in range(N):
  b= []
  for j in range(N):
    k = input()
    b.append(float(k))
  a.append(b)
a

2
1.1
1.1
.1
1.1


[[1.1, 1.1], [0.1, 1.1]]

In [0]:
n=5
a[n]=input().split(" ")

In [42]:
x = 'blue,red,green'
a,b,c = x.split(',')

print(a)
print(b)
print(c)

blue
red
green


In [43]:
x = 'blue red green'
a,b,c = x.split(' ')

print(a)
print(b)
print(c)

blue
red
green


In [44]:
x = input()

I am a boy


In [45]:
x,y,z = input().split(' ')
print(x)
print(y)
print(z)

1 2 3
1
2
3


In [46]:
string = ' Wecome in India '
string.split()

['Wecome', 'in', 'India']

In [50]:
string = ' Wecome in India '
string.split(" ")   # seperate the spaces.

['', 'Wecome', 'in', 'India', '']

In [0]:
import numpy
n=int(input())
a=numpy.array([input().split() for _ in range(n)],float)
numpy.set_printoptions(legacy='1.13') #important   # for round up the floating value upto 2 digits
print(numpy.linalg.det(a))

In [7]:
nums =map(int, input().split())
nums

1 2 3 4 5


In [9]:
list(nums)

[]

tuple() is unchangeable/ immutable data type in python .  
it can not be converted into list and vice-versa.

In [8]:
tuple(nums)

(1, 2, 3, 4, 5)

The poly tool returns the coefficients of a polynomial with the given sequence of roots.

In [12]:
import numpy
numpy.poly([-1, 1, 1, 10]) 

array([  1., -11.,   9.,  11., -10.])

#roots
The roots tool returns the roots of a polynomial with the given coefficients.

In [13]:
numpy.roots([1, 0, -1])   

array([-1.,  1.])

#polyval()
The polyval tool evaluates the polynomial at specific position.

In [16]:
numpy.polyval([1, -2, 0, 2], 4) 

34

#set()  function
 
 python opration

In [26]:
people = {"Jay", "Idrish", "Archil"}
vampires = {"Karan", "Arjun"}
population = people.union(vampires)
print(population)
print(people|vampires)

{'Archil', 'Idrish', 'Jay', 'Arjun', 'Karan'}
{'Archil', 'Idrish', 'Jay', 'Arjun', 'Karan'}


In [23]:
print(people.intersection(vampires))

set()


In [28]:
# difference(s) Method: 
safe = people.difference(vampires)
print(safe)

{'Archil', 'Idrish', 'Jay'}


In [35]:
A = {1,2 ,3, 5 ,6} 
B = {9 ,8, 5 ,6 ,3, 2, 1, 4, 7} 
print(A-B)
print(A-B ==set())
print ((A | B) == B)
print((A | B)-B )
print ((A | B)-B == set())
print( A==(A&B))   # intersection

set()
True
True
set()
True
True


In [39]:
k = set(input().split())

1 2 4 5 6 79 7 8 93 1 4


In [40]:
k

{'1', '2', '4', '5', '6', '7', '79', '8', '93'}

In [48]:
p = set((int , input().split()))
print(p)

1 2 3 4 5 4 7 81 4 5 6 2 1 4 5 5 6 1 2


In [46]:
list(p)

[1, 2, 4, 5, 6, 79, 7, 8, 93, 1, 4]

In [49]:
set(p)

{1, 2, 3, 4, 5, 6, 7, 81}

In [53]:
n =int(input())
arr = [int(input()) for _ in range(n)]
arr = set(arr)
print(arr)

5
1
2
3
2
1
{1, 2, 3}


In [56]:
a = set([1,8,9,7,3,6,4])
print(a)

{1, 3, 4, 6, 7, 8, 9}


In [74]:
word = 'helloworld'
set_opt = set(word) 
set_opt

{'d', 'e', 'h', 'l', 'o', 'r', 'w'}

In [75]:
addtion = set_opt.add('hacker')
set_opt

{'d', 'e', 'h', 'hacker', 'l', 'o', 'r', 'w'}

In [0]:

n,m = input().split()
n = int(n)
m = int(m)

like = 0   # at initial state 
dislike = 0  # at initial state 
arr = set(map(int,input().split()))
A = set(map(int,input().split())) # like  = 1
B = set(map(int,input().split()))  # dislike = -1

for i in A.intersection(arr):
    like = like +1
for i in B.intersection(arr):
    dislike = dislike -1
print(like+dislike)     # total happiness

#print(sum([(i in A) - (i in B) for i in arr]))



In [82]:
s = set("Hacker")
s

{'H', 'a', 'c', 'e', 'k', 'r'}

In [84]:
s.union("Rank")

{'H', 'R', 'a', 'c', 'e', 'k', 'n', 'r'}

In [87]:
list(enumerate(['R', 'k', 'a', 'n']))

[(0, 'R'), (1, 'k'), (2, 'a'), (3, 'n')]

In [80]:
for _ in range(5):
  k = '{0}{1}'.format(*input().split())  # remove the single quote from of string
  print(k)

hello 4
hello4
joker 4
joker4
rahul 4
rahul4
kolmal 4
kolmal4
priya 2
priya2
