<a href="https://colab.research.google.com/github/priyanshgupta1998/All_codes/blob/master/decision_tree0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree

In [11]:
#loding data file
data_load = pd.read_csv('/home/loans.csv')
print(data_load[0:4])

   credit.policy             purpose  int.rate  installment  log.annual.inc  \
0              1  debt_consolidation    0.1189       829.10       11.350407   
1              1         credit_card    0.1071       228.22       11.082143   
2              1  debt_consolidation    0.1357       366.86       10.373491   
3              1  debt_consolidation    0.1008       162.34       11.350407   

     dti  fico  days.with.cr.line  revol.bal  revol.util  inq.last.6mths  \
0  19.48   737        5639.958333      28854        52.1             0.0   
1  14.29   707        2760.000000      33623        76.7             0.0   
2  11.63   682        4710.000000       3511        25.6             1.0   
3   8.10   712        2699.958333      33667        73.2             1.0   

   delinq.2yrs  pub.rec  not.fully.paid  
0          0.0      0.0               0  
1          0.0      0.0               0  
2          0.0      0.0               0  
3          0.0      0.0               0  


In [7]:
balanced_data =  pd.read_csv('/home/loans.csv' , sep=',' , header = 0 )
print(balanced_data[0:4])

   credit.policy             purpose  int.rate  installment  log.annual.inc  \
0              1  debt_consolidation    0.1189       829.10       11.350407   
1              1         credit_card    0.1071       228.22       11.082143   
2              1  debt_consolidation    0.1357       366.86       10.373491   
3              1  debt_consolidation    0.1008       162.34       11.350407   

     dti  fico  days.with.cr.line  revol.bal  revol.util  inq.last.6mths  \
0  19.48   737        5639.958333      28854        52.1             0.0   
1  14.29   707        2760.000000      33623        76.7             0.0   
2  11.63   682        4710.000000       3511        25.6             1.0   
3   8.10   712        2699.958333      33667        73.2             1.0   

   delinq.2yrs  pub.rec  not.fully.paid  
0          0.0      0.0               0  
1          0.0      0.0               0  
2          0.0      0.0               0  
3          0.0      0.0               0  


In [8]:
print("dataset_length : ",len(balanced_data))

dataset_length :  9578


In [9]:
print("shape of dataset: ",balanced_data.shape)

shape of dataset:  (9578, 14)


In [19]:
x=balanced_data.values[0:4,0:4]
print(x)

[[1 'debt_consolidation' 0.1189 829.1]
 [1 'credit_card' 0.1071 228.22]
 [1 'debt_consolidation' 0.1357 366.86]
 [1 'debt_consolidation' 0.1008 162.34]]


In [18]:
x=balanced_data.values[0:4,3]
print(x)

[829.1 228.22 366.86 162.34]


In [34]:
#seperating the Target variable
X=balanced_data.values[:,2:6]
print(X)

[[0.1189 829.1 11.35040654 19.48]
 [0.1071 228.22 11.08214255 14.29]
 [0.1357 366.86 10.37349118 11.63]
 ...
 [0.1071 97.81 10.59663473 13.09]
 [0.16 351.58 10.81977828 19.18]
 [0.1392 853.43 11.26446411 16.28]]


In [35]:
#seperating the Target variable
Y=balanced_data.values[:,0]
print(Y)

[1 1 1 ... 0 0 0]


In [0]:
#Spliting dataset into Test and Train
#Build a decision tree
X_train , X_test , Y_train , Y_test = train_test_split(X,Y, test_size=0.3 , random_state=0)

In [105]:
print(X_train[0:5])

[[0.0768 155.95 10.59663473 11.49]
 [0.1287 94.18 10.72161404 3.52]
 [0.1189 505.76 11.40756495 9.44]
 [0.1114 360.84 10.75773265 10.39]
 [0.1218 149.85 11.33857208 0.07]]


In [106]:
print(X_test[0:5])

[[0.1189 49.75 10.82972862 16.87]
 [0.1221 84.12 10.20359214 10.0]
 [0.1695 712.54 11.91839057 13.61]
 [0.1739 286.78 11.18996158 19.59]
 [0.1312 202.51 9.392661928999999 4.4]]


In [107]:
print(Y_train[0:5])

[1 1 1 1 1]


In [108]:
print(Y_test[0:5])

[1 1 1 1 0]


In [109]:
print(X[0:5])
print(X[0][0:5])  # raw and column 
print(X[1][0:2])
print(np.isinf(list(X[1][0:2])))  # convert a metrix into list.

[[0.1189 829.1 11.35040654 19.48]
 [0.1071 228.22 11.08214255 14.29]
 [0.1357 366.86 10.37349118 11.63]
 [0.1008 162.34 11.35040654 8.1]
 [0.1426 102.92 11.29973224 14.97]]
[0.1189 829.1 11.35040654 19.48]
[0.1071 228.22]
[False False]


In [110]:
print(len(X_train))

6704


In [111]:
#X_train.any(np.isnan(X_train))   # only use for list elements 
#print(np.all(np.isfinite((X_train)))  # only use for list elements 
#print(np.isinf(X))
#print(np.isnan(X))
for i in range(len(X_train)):
  print(np.isinf(list(X_train[i])))
    

[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False

In [112]:
for i in range(len(X_train)):
  print(np.isnan(list(X_train[i])))

[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False False False]
[False False

In [116]:
for i in range(len(X_train[0:5])):
  #print(np.isfinite(X_train[i].any()))
  if (np.isfinite(X_train[i].any()) == True):
    print('on')
    

on
on
on
on
on


In [114]:
#Function to perform training with entropy
clf_entropy = DecisionTreeClassifier(criterion = 'entropy' , random_state=0,
                                    max_depth=3,min_samples_leaf = 5)
print(clf_entropy)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')


In [119]:
clf_entropy.fit(X_train , Y_train  )

ValueError: ignored

In [89]:
import numpy as np
test = np.array([0.1, 0.3, float("Inf"), 0.2])
print(test)
print(np.isinf(test))
bad_indices = np.where(np.isinf(test))
print(bad_indices)

[0.1 0.3 inf 0.2]
[False False  True False]
(array([2]),)
