<a href="https://colab.research.google.com/github/priyanshgupta1998/All_codes/blob/master/decision_tree1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree

In [11]:
#loding data file
data_load = pd.read_csv('/home/loans.csv')
print(data_load[0:4])

   credit.policy             purpose  int.rate  installment  log.annual.inc  \
0              1  debt_consolidation    0.1189       829.10       11.350407   
1              1         credit_card    0.1071       228.22       11.082143   
2              1  debt_consolidation    0.1357       366.86       10.373491   
3              1  debt_consolidation    0.1008       162.34       11.350407   

     dti  fico  days.with.cr.line  revol.bal  revol.util  inq.last.6mths  \
0  19.48   737        5639.958333      28854        52.1             0.0   
1  14.29   707        2760.000000      33623        76.7             0.0   
2  11.63   682        4710.000000       3511        25.6             1.0   
3   8.10   712        2699.958333      33667        73.2             1.0   

   delinq.2yrs  pub.rec  not.fully.paid  
0          0.0      0.0               0  
1          0.0      0.0               0  
2          0.0      0.0               0  
3          0.0      0.0               0  


In [7]:
balanced_data =  pd.read_csv('/home/loans.csv' , sep=',' , header = 0 )
print(balanced_data[0:4])

   credit.policy             purpose  int.rate  installment  log.annual.inc  \
0              1  debt_consolidation    0.1189       829.10       11.350407   
1              1         credit_card    0.1071       228.22       11.082143   
2              1  debt_consolidation    0.1357       366.86       10.373491   
3              1  debt_consolidation    0.1008       162.34       11.350407   

     dti  fico  days.with.cr.line  revol.bal  revol.util  inq.last.6mths  \
0  19.48   737        5639.958333      28854        52.1             0.0   
1  14.29   707        2760.000000      33623        76.7             0.0   
2  11.63   682        4710.000000       3511        25.6             1.0   
3   8.10   712        2699.958333      33667        73.2             1.0   

   delinq.2yrs  pub.rec  not.fully.paid  
0          0.0      0.0               0  
1          0.0      0.0               0  
2          0.0      0.0               0  
3          0.0      0.0               0  


In [8]:
print("dataset_length : ",len(balanced_data))

dataset_length :  9578


In [9]:
print("shape of dataset: ",balanced_data.shape)

shape of dataset:  (9578, 14)


In [19]:
x=balanced_data.values[0:4,0:4]
print(x)

[[1 'debt_consolidation' 0.1189 829.1]
 [1 'credit_card' 0.1071 228.22]
 [1 'debt_consolidation' 0.1357 366.86]
 [1 'debt_consolidation' 0.1008 162.34]]


In [18]:
x=balanced_data.values[0:4,3]
print(x)

[829.1 228.22 366.86 162.34]


In [151]:
#seperating the Target variable
X=balanced_data.values[:,2:4]
print(X)

[[0.1189 829.1]
 [0.1071 228.22]
 [0.1357 366.86]
 ...
 [0.1071 97.81]
 [0.16 351.58]
 [0.1392 853.43]]


In [152]:
#seperating the Target variable
Y=balanced_data.values[:,0]
Y=Y.astype('int')  # define the data type of 'classifier / output / predicted_value'
print(Y)

[1 1 1 ... 0 0 0]


In [0]:
#Spliting dataset into Test and Train
#Build a decision tree
X_train , X_test , Y_train , Y_test = train_test_split(X,Y, test_size=0.3 , random_state=100)

In [154]:
print(X_train[0:5])

[[0.1189 49.75]
 [0.0976 305.47]
 [0.1411 171.15]
 [0.1126 312.21]
 [0.0894 285.95]]


In [155]:

#Function to perform training with entropy
clf_entropy = DecisionTreeClassifier(criterion = 'entropy' , random_state=100,
                                    max_depth=3,min_samples_leaf = 5)
print(clf_entropy)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')


In [156]:
clf_entropy.fit(X_train , Y_train  )

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=5, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=100,
            splitter='best')

In [157]:
#Function_to_make_predictions
y_pred_en = clf_entropy.predict(X_test)
print(y_pred_en)

[1 1 1 ... 1 1 1]


In [158]:
#Checking Accuracy
print(accuracy_score(Y_test , y_pred_en))

0.8051496172581768


In [159]:
print(accuracy_score(Y_test , y_pred_en)*100)

80.51496172581768
