<a href="https://colab.research.google.com/github/priyanshgupta1998/All_codes/blob/master/indico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**indico** --> Indico allows you to schedule conferences, from single talks to complex meetings with sessions and contributions. It also includes an advanced user delegation mechanism, allows paper reviewing, archival of conference information and electronic proceedings

password:  Hacker@123

In [6]:
#!pip install indicoio
indicoio.__version__

'1.2.0'

In [7]:
import indicoio
indicoio.config.api_key = '7faceae31085edfdaf927f4771ba1df9'

# Version >= 0.9.0
indicoio.sentiment(['indico is so easy to use!', 'Still really easy, yiss'])

# Version < 0.9.0
#indicoio.batch_sentiment(['indico is so easy to use!', 'Still really easy, yiss'])


[0.9782025594088044, 0.9895808115135271]

`This function will return a number between 0 and 1. This number is a probability representing the likelihood that the analyzed text is positive or negative. Values greater than 0.5 indicate positive sentiment, while values less than 0.5 indicate negative sentiment.`

In [14]:
# single example
print(indicoio.sentiment("I love and hate her"))


print(indicoio.sentiment("I hate him"))


print(indicoio.sentiment("I hate cruel sad unlucky"))


# batch example
indicoio.sentiment([
    "I love writing code!",
    "Alexander and the Terrible, Horrible, No Good, Very Bad Day"
])

0.8347072549358285
0.4195634282951124
0.00955951544644467


[0.9819219949985644, 0.00015202198176385973]

###High Quality Sentiment Analysis

`Highly accurate sentiment analysis but less performant than the standard Sentiment API. Note: Sentiment HQ only supports English analysis. For multilingual support, please use the standard Sentiment API.`

In [19]:
# single example
print(indicoio.sentiment_hq("I love writing code!"))

# batch example
indicoio.sentiment_hq([
    "I love writing code!",
    "Alexander and the Terrible, Horrible, No Good, Very Bad Day"
])

0.9903809


[0.9892174, 0.0034347023]

In [18]:
# single example
print(indicoio.sentiment_hq("أحب كتابة الكود!"))      #I love writing code!


0.8034777


##Text Tags 
`This function will return a dictionary with 111 key-value pairs. These key-value pairs represent the likelihood that the analyzed text is about each of the 111 possible topics. The keys in the dictionary are strings containing the topic names and the values are the probabilities that the analyzed text is about each topic.`

In [22]:
# single example
print(len(indicoio.text_tags("The most common form of arrow consists of a shaft with an arrowhead attached to the front end and with fletchings and a \
                   nock attached to the other end.")))

print(indicoio.text_tags("The most common form of arrow consists of a shaft with an arrowhead attached to the front end and with fletchings and a \
                   nock attached to the other end."))

111
{'archery': 0.9980742931365967, 'hunting': 0.0009959941962733865, 'guns': 0.00047092887689359486, 'golf': 0.00018577380978967994, 'tennis': 5.92623146076221e-05, 'crafts': 2.980339922942221e-05, 'biology': 2.1638661564793438e-05, 'climbing': 1.6889678590814583e-05, 'cricket': 1.364311629004078e-05, 'fishing': 1.3066501196590252e-05, 'weight_training': 1.005332978820661e-05, 'ultimate': 9.978061825677287e-06, 'DIY': 8.521928066329565e-06, 'math': 8.209718544094358e-06, 'poker': 7.68693189456826e-06, 'medicine': 5.9809794947796036e-06, 'electronics': 5.378122295951471e-06, 'photography': 5.254831194179133e-06, 'gaming': 4.941529368807096e-06, 'fitness': 4.018845629616408e-06, 'tattoo': 4.010705197288189e-06, 'military': 3.7830398014193634e-06, 'programming': 3.5740465591516113e-06, 'gardening': 3.016925347765209e-06, 'astronomy': 2.8555145945574623e-06, 'anime': 2.345488837818266e-06, 'singing': 1.919170927067171e-06, 'sports': 1.6779662246335647e-06, 'art': 1.5552134300378384e-06, '

In [23]:
# batch example

print(len(indicoio.text_tags([
    "The most common form of arrow consists of a shaft with an arrowhead attached to the front end and with fletchings and a nock attached to the other end.",
    "Yoga in Indian traditions, however, is more than physical exercise, it has a meditative and spiritual core."
])))

print(indicoio.text_tags([
    "The most common form of arrow consists of a shaft with an arrowhead attached to the front end and with fletchings and a nock attached to the other end.",
    "Yoga in Indian traditions, however, is more than physical exercise, it has a meditative and spiritual core."
]))


2
[{'archery': 0.9980742931365967, 'hunting': 0.0009959933813661337, 'guns': 0.0004709286440629512, 'golf': 0.00018577380978967994, 'tennis': 5.92623146076221e-05, 'crafts': 2.980339922942221e-05, 'biology': 2.1638661564793438e-05, 'climbing': 1.6889678590814583e-05, 'cricket': 1.364311629004078e-05, 'fishing': 1.3066501196590252e-05, 'weight_training': 1.005332978820661e-05, 'ultimate': 9.978061825677287e-06, 'DIY': 8.521919880877249e-06, 'math': 8.209718544094358e-06, 'poker': 7.68693189456826e-06, 'medicine': 5.9809794947796036e-06, 'electronics': 5.378122295951471e-06, 'photography': 5.254831194179133e-06, 'gaming': 4.941534371027956e-06, 'fitness': 4.018845629616408e-06, 'tattoo': 4.010705197288189e-06, 'military': 3.7830398014193634e-06, 'programming': 3.5740465591516113e-06, 'gardening': 3.016925347765209e-06, 'astronomy': 2.8555145945574623e-06, 'anime': 2.345488837818266e-06, 'singing': 1.919170927067171e-06, 'sports': 1.6779662246335647e-06, 'art': 1.5552134300378384e-06, 'sa

###Language Detection

`This function will return a dictionary with 33 key-value pairs. These key-value pairs represent the likelihood that the analyzed text is written in each of the 33 possible languages. The keys in the dictionary are strings containing the language names and the values are the probabilities that the analyzed text is written in each language.`
`Values less than 0.05 indicate that it is very unlikely the text is written in the corresponding language.`

**Complete List of Languages:**
`Arabic (ar), Bulgarian (bg), Chinese (ch), Czech (cs), Danish (da), Dutch (nl), English (en), Esparanto (eo), Farsi (fa), Finnish (fi), French (fr), German (de), Greek (el), Hebrew (he), Hungarian (hu), Indonesian (id), Italian (it), Japanese (ja), Korean (ko), Latin (la), Lithuanian (lt), Norwegian (no), Polish (pl), Portuguese (pg), Romanian (ro), Russian (ru), Slovak (sk), Spanish (es), Swedish (sv), Tagalog (tl), Thai (th), Turkish (tr), Vietnamese (vi)`

In [25]:
# single example
print(indicoio.language("How are you?"))


{'English': 0.9990728163207458, 'Romanian': 0.00015268149532874959, 'Norwegian': 0.00014253643487109044, 'Finnish': 0.00011696538630045383, 'Portuguese': 0.00011649853788855026, 'Tagalog': 9.96739365897255e-05, 'Danish': 8.095553753042332e-05, 'Italian': 6.223770851264582e-05, 'Polish': 3.2565649068767874e-05, 'German': 2.7590010072508947e-05, 'Hungarian': 2.2149399653570215e-05, 'Spanish': 2.0946113035684788e-05, 'French': 1.6267043319641448e-05, 'Czech': 1.3528307431831818e-05, 'Chinese': 5.919979123033187e-06, 'Turkish': 5.38873419001694e-06, 'Indonesian': 4.93815140900782e-06, 'Japanese': 3.7956995057615573e-06, 'Slovak': 6.298966868415444e-07, 'Swedish': 6.07621211789679e-07, 'Esperanto': 4.924878564275682e-07, 'Dutch': 3.345693239921886e-07, 'Thai': 1.7447121922892275e-07, 'Lithuanian': 1.5299913843838884e-07, 'Vietnamese': 9.394912159751473e-08, 'Latin': 4.101134010774466e-08, 'Korean': 6.963605641636501e-09, 'Greek': 5.1017263237892425e-09, 'Bulgarian': 4.383902049976359e-09, '

In [26]:
# batch example
print(indicoio.language([
    "How are you?",
    "¿Cómo estás?"
]))

[{'English': 0.9990728163207458, 'Romanian': 0.00015268149532874959, 'Norwegian': 0.00014253643487109044, 'Finnish': 0.00011696538630045383, 'Portuguese': 0.00011649853788855026, 'Tagalog': 9.96739365897255e-05, 'Danish': 8.095553753042332e-05, 'Italian': 6.223770851264582e-05, 'Polish': 3.2565649068767874e-05, 'German': 2.7590010072508947e-05, 'Hungarian': 2.2149399653570215e-05, 'Spanish': 2.0946113035684788e-05, 'French': 1.6267043319641448e-05, 'Czech': 1.3528307431831818e-05, 'Chinese': 5.919979123033187e-06, 'Turkish': 5.38873419001694e-06, 'Indonesian': 4.93815140900782e-06, 'Japanese': 3.7956995057615573e-06, 'Slovak': 6.298966868415444e-07, 'Swedish': 6.07621211789679e-07, 'Esperanto': 4.924878564275682e-07, 'Dutch': 3.345693239921886e-07, 'Thai': 1.7447121922892275e-07, 'Lithuanian': 1.5299913843838884e-07, 'Vietnamese': 9.394912159751473e-08, 'Latin': 4.101134010774466e-08, 'Korean': 6.963605641636501e-09, 'Greek': 5.1017263237892425e-09, 'Bulgarian': 4.383902049976359e-09, 

###Political Analysis
This function will return a dictionary with 4 key-value pairs. These key-value pairs represent the likelihood that each of 4 political leanings are expressed in the analyzed text. The keys in the dictionary are strings containing the political leanings and the values are the probabilities that the analyzed text is expressing each political view.

Values less than 0.05 indicate that it is very unlikely the text is expressing that particular political leaning.

In [27]:
# single example
indicoio.political("I have a constitutional right to bear arms!")

{'Conservative': 0.19319603,
 'Green': 0.32515985,
 'Liberal': 0.11416193,
 'Libertarian': 0.3674822}

In [28]:
# batch example
indicoio.political([
"I have a constitutional right to bear arms!",
"I wish more candidates cared about the environment."
])

[{'Conservative': 0.19319604,
  'Green': 0.32515982,
  'Liberal': 0.11416193,
  'Libertarian': 0.3674822},
 {'Conservative': 0.031118236,
  'Green': 0.8877605,
  'Liberal': 0.03157693,
  'Libertarian': 0.049544327}]

###Keywords Detection
Identify the important words within a document.  
This function will return a dictionary with top_n key-value pairs.   
These key-value pairs represent the likelihood that each of the extracted keywords are relevant to the analyzed text.    
The keys in the dictionary are strings containing the extracted keywords, and the values are the likelihoods that how much these keywords are relevant to the analyzed text.

In [30]:
# single example
indicoio.keywords("Some call it the sunshine state", version=4)

{'state': 0.7071067811865475, 'sunshine': 0.7071067811865475}

In [33]:
# batch example
indicoio.keywords([
    "Some call it the sunshine state",
    "you should tell truth to everyone. India is very religious country."
], version=4)

[{'state': 0.7071067811865475, 'sunshine': 0.7071067811865475},
 {'country': 0.4989927078129315,
  'religious': 0.498992707812931,
  'tell': 0.4989927078129308,
  'truth': 0.4989927078129311}]

In [34]:


# single example
indicoio.people("London Underground's boss Mike Brown warned that the strike ...")

[{'confidence': 0.8003784418106079,
  'position': [26, 36],
  'text': 'Mike Brown'}]

In [43]:
indicoio.people("London Underground's Tom Cruise and Mohit Brown warned that Nobody will run away from here on Robert De Niro birthday ...")

[{'confidence': 0.7230064272880554,
  'position': [21, 31],
  'text': 'Tom Cruise'},
 {'confidence': 0.8640574216842651,
  'position': [36, 47],
  'text': 'Mohit Brown'},
 {'confidence': 0.7257371544837952,
  'position': [94, 108],
  'text': 'Robert De Niro'}]

In [80]:
# single example
indicoio.analyze_text("Democratic candidate Hillary Clinton is excited for the upcoming election.", apis=['sentiment_hq', 'political'])

{'political': {'Conservative': 0.33317617,
  'Green': 0.21979073,
  'Liberal': 0.22697456,
  'Libertarian': 0.22005858},
 'sentiment_hq': 0.73005515}

In [83]:
# single example
indicoio.emotion("I did it. I got into Grad School. Not just any program, but a GREAT program.:-) ")

{'anger': 0.007581708952784538,
 'fear': 0.0701667070388794,
 'joy': 0.8000515103340149,
 'sadness': 0.025123823434114456,
 'surprise': 0.09707625210285187}

#4.Image Analysis
**Input Image Format**
`Images can be sent to the indicoio image analysis functions as URLs, file paths, base64 encoded images, numpy array objects, or skimage image objects. Sample code for loading in an image using skimage or PIL is provided below. Although images are scaled on our servers, use square crops for optimal performance. Both single and batch image requests of over 15 MB will be rejected.`

In [46]:
#using local image
#indicoio.fer('FILEPATH')

#using link
indicoio.fer('https://images.pexels.com/photos/56866/garden-rose-red-pink-56866.jpeg?cs=srgb&dl=bloom-blossom-dew-56866.jpg&fm=jpg')

{'Angry': 0.004700957797467709,
 'Fear': 0.05888555198907852,
 'Happy': 0.23306000232696533,
 'Neutral': 0.6466555595397949,
 'Sad': 0.041299160569906235,
 'Surprise': 0.015398768708109856}

In [47]:
indicoio.fer('https://images.pexels.com/photos/1187079/pexels-photo-1187079.jpeg?cs=srgb&dl=beautiful-bloom-blooming-1187079.jpg&fm=jpg')

{'Angry': 0.43779656291007996,
 'Fear': 0.010972879827022552,
 'Happy': 0.4385334551334381,
 'Neutral': 0.023337870836257935,
 'Sad': 0.08771135658025742,
 'Surprise': 0.001647816738113761}

In [50]:
cd /home

/home


In [64]:
!wget https://images.pexels.com/photos/1187079/pexels-photo-1187079.jpeg?cs=srgb&dl=beautiful-bloom-blooming-1187079.jpg&fm=jpg
import skimage.io
pixel_array = skimage.io.imread('pexels-photo-1187079.jpeg?cs=srgb')
print(pixel_array.shape)
print(pixel_array[0])
print(type(pixel_array))
import numpy as np
pic = np.array(pixel_array)
print(type(pic))
print(pic.shape)
print(pic[0])
indicoio.fer(pic)

(6000, 4000, 3)
[[16 35 41]
 [14 31 38]
 [11 28 35]
 ...
 [12 17 23]
 [13 16 23]
 [14 17 24]]
<class 'imageio.core.util.Array'>
<class 'numpy.ndarray'>
(6000, 4000, 3)
[[16 35 41]
 [14 31 38]
 [11 28 35]
 ...
 [12 17 23]
 [13 16 23]
 [14 17 24]]


{'Angry': 0.5135629773139954,
 'Fear': 0.01342673972249031,
 'Happy': 0.4646221101284027,
 'Neutral': 0.003108732169494033,
 'Sad': 0.005167318042367697,
 'Surprise': 0.00011212808021809906}

In [0]:
#Formatting images using PIL and numpy
from PIL import Image
import PIL
import numpy as np
import indicoio

image = PIL.imread('pexels-photo-1187079.jpeg?cs=srgb')
pixel_array = np.array(image)

indicoio.fer(pixel_array)

###Facial Emotion Recognition
Determine the emotions expressed in an image of a human face.       

This function will return a dictionary with 6 key-value pairs. These key-value pairs represent the likelihood that each of 6 detectable emotions are expressed by the face in the analyzed image.   
The keys in the dictionary are strings containing the emotions (Angry, Sad, Neutral, Surprise, Fear, Happy) and the values are the probabilities that the face in the analyzed image is expressing each emotion.       

Values less than 0.05 indicate that it is very unlikely the face is expressing the corresponding emotion.       

Using the detect flag changes output format: When using the detect flag the results returned will be a list of dictionaries. Each dictionary in the list corresponds to a detected face. Each dictionary has two key-value pairs, the keys are “emotions” and “location”.     

The value of “emotions” is the same dictionary described above with 6 key-value pairs. The value of “location” is the bounding box of the detected face in the form [x position of top left corner, y position of top-left corner, width of bounding box, height of bounding box].

In [76]:
# single example
indicoio.fer("/home/image1.jpg")

{'Angry': 0.01307767815887928,
 'Fear': 0.14489752054214478,
 'Happy': 0.0946243405342102,
 'Neutral': 0.09810975193977356,
 'Sad': 0.6487656235694885,
 'Surprise': 0.0005250137764960527}

###Image Features

In [78]:
print(len(indicoio.image_features("/home/image1.jpg")))
print(indicoio.image_features("/home/image1.jpg"))

4096
[0.0, 0.0, 0.0, 0.0, 0.0, 0.13524112105369568, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.8498592376708984, 0.0, 0.0, 0.03125347942113876, 0.0, 0.0, 0.0, 0.3473680019378662, 0.0, 0.0, 0.2834927439689636, 0.2906728684902191, 0.0, 0.863910973072052, 0.0, 0.0, 0.27235016226768494, 0.0, 0.17011816799640656, 0.0, 0.0, 0.04766547307372093, 0.0, 0.0, 0.0, 0.001614749664440751, 0.0, 0.0, 0.0, 0.0, 0.9341238141059875, 0.053285978734493256, 0.0, 0.21325445175170898, 0.0, 1.459265947341919, 0.582239031791687, 0.0, 0.030023057013750076, 0.0, 0.03604622185230255, 0.0, 0.032350946217775345, 0.0, 0.006989414803683758, 0.0, 0.0, 0.0, 0.0, 0.0, 0.15034575760364532, 0.0, 0.0, 0.0, 0.0, 0.2889862358570099, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5985455513000488, 0.0, 0.0, 0.055044692009687424, 0.0, 0.0, 0.2327987253665924, 0.9412202835083008, 0.0, 0.0, 0.0, 0.1334795206785202, 0.0, 0.0, 0.12433604896068573, 0.0, 0.3542284369468689, 0.0, 0.02438320592045784, 0.0, 0.0, 0.0, 0.0, 0.0, 

In [79]:
!wget http://www.arvindguptatoys.com/arvindgupta/rbi-comic.pdf
# single example
indicoio.pdf_extraction("rbi-comic.pdf")

--2019-05-26 15:58:34--  http://www.arvindguptatoys.com/arvindgupta/rbi-comic.pdf
Resolving www.arvindguptatoys.com (www.arvindguptatoys.com)... 146.66.94.13
Connecting to www.arvindguptatoys.com (www.arvindguptatoys.com)|146.66.94.13|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6124866 (5.8M) [application/pdf]
Saving to: ‘rbi-comic.pdf’

rbi-comic.pdf       100%[===================>]   5.84M  3.13MB/s    in 1.9s    

2019-05-26 15:58:38 (3.13 MB/s) - ‘rbi-comic.pdf’ saved [6124866/6124866]



{'images': [],
 'metadata': {'creationdate': '',
  'creator': 'CorelDRAW Version 12.0',
  'encrypted': 'no',
  'file size': '6124866 bytes',
  'form': 'none',
  'moddate': '',
  'optimized': 'yes',
  'page size': '1190.55 x 841.89 pts (rotated 0 degrees)',
  'pages': '10',
  'pdf version': '1.3',
  'producer': 'Corel PDF Engine Version 1.0.0.458',
  'tagged': 'no',
  'title': 'English Comics'},
 'text': ''}