<a href="https://colab.research.google.com/github/priyanshgupta1998/All_codes/blob/master/List_Numpy_concept.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Using Pandas to Get Familiar With Your Data

Python is a pretty versatile language. 

`The first step in any machine learning project is familiarize yourself with the data. You'll use the Pandas library for this. Pandas is the primary tool data scientists use for exploring and manipulating data`.

The most important part of the Pandas library is the DataFrame. A DataFrame holds the type of data you might think of as a table. This is similar to a sheet in Excel, or a table in a SQL database.

In [0]:
import pandas as pd

In [34]:
df = pd.read_csv('/home/melb_data.csv') 
df.head()

Suburb           Address  Rooms Type      Price Method SellerG  \
0  Abbotsford      85 Turner St      2    h  1480000.0      S  Biggin   
1  Abbotsford   25 Bloomburg St      2    h  1035000.0      S  Biggin   
2  Abbotsford      5 Charles St      3    h  1465000.0     SP  Biggin   
3  Abbotsford  40 Federation La      3    h   850000.0     PI  Biggin   
4  Abbotsford       55a Park St      4    h  1600000.0     VB  Nelson   

        Date  Distance  Postcode      ...       Bathroom  Car  Landsize  \
0  3/12/2016       2.5    3067.0      ...            1.0  1.0     202.0   
1  4/02/2016       2.5    3067.0      ...            1.0  0.0     156.0   
2  4/03/2017       2.5    3067.0      ...            2.0  0.0     134.0   
3  4/03/2017       2.5    3067.0      ...            2.0  1.0      94.0   
4  4/06/2016       2.5    3067.0      ...            1.0  2.0     120.0   

   BuildingArea  YearBuilt  CouncilArea Lattitude  Longtitude  \
0           NaN        NaN        Yarra  -37.7996    144.9984   
1          79.0     1900.0        Yarra  -37.8079    144.9934   
2         150.0     1900.0        Yarra  -37.8093    144.9944   
3           NaN        NaN        Yarra  -37.7969    144.9969   
4         142.0     2014.0        Yarra  -37.8072    144.9941   

              Regionname Propertycount  
0  Northern Metropolitan        4019.0  
1  Northern Metropolitan        4019.0  
2  Northern Metropolitan        4019.0  
3  Northern Metropolitan        4019.0  
4  Northern Metropolitan        4019.0  

[5 rows x 21 columns]

In [35]:
print(df.shape)
print(type(df))
print(df.ndim)
print(len(df))

(13580, 21)
<class 'pandas.core.frame.DataFrame'>
2
13580


In [48]:
df.describe()   # summary of the whole dataset    #remove redundant columns from the dataset and calculate the overview about the result

Rooms         Price      Distance      Postcode      Bedroom2  \
count  13580.000000  1.358000e+04  13580.000000  13580.000000  13580.000000   
mean       2.937997  1.075684e+06     10.137776   3105.301915      2.914728   
std        0.955748  6.393107e+05      5.868725     90.676964      0.965921   
min        1.000000  8.500000e+04      0.000000   3000.000000      0.000000   
25%        2.000000  6.500000e+05      6.100000   3044.000000      2.000000   
50%        3.000000  9.030000e+05      9.200000   3084.000000      3.000000   
75%        3.000000  1.330000e+06     13.000000   3148.000000      3.000000   
max       10.000000  9.000000e+06     48.100000   3977.000000     20.000000   

           Bathroom           Car       Landsize  BuildingArea    YearBuilt  \
count  13580.000000  13518.000000   13580.000000   7130.000000  8205.000000   
mean       1.534242      1.610075     558.416127    151.967650  1964.684217   
std        0.691712      0.962634    3990.669241    541.014538    37.273762   
min        0.000000      0.000000       0.000000      0.000000  1196.000000   
25%        1.000000      1.000000     177.000000     93.000000  1940.000000   
50%        1.000000      2.000000     440.000000    126.000000  1970.000000   
75%        2.000000      2.000000     651.000000    174.000000  1999.000000   
max        8.000000     10.000000  433014.000000  44515.000000  2018.000000   

          Lattitude    Longtitude  Propertycount  
count  13580.000000  13580.000000   13580.000000  
mean     -37.809203    144.995216    7454.417378  
std        0.079260      0.103916    4378.581772  
min      -38.182550    144.431810     249.000000  
25%      -37.856822    144.929600    4380.000000  
50%      -37.802355    145.000100    6555.000000  
75%      -37.756400    145.058305   10331.000000  
max      -37.408530    145.526350   21650.000000



```
To interpret the min, 25%, 50%, 75% and max values, imagine sorting each column from lowest to highest value. The first (smallest) value is the min. If you go a quarter way through the list, you'll find a number that is bigger than 25% of the values and smaller than 75% of the values. That is the 25% value (pronounced "25th percentile"). The 50th and 75th percentiles are defined analogously, and the max is the largest number.
```



In [49]:
print(df.describe().shape)

(8, 13)


In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
Suburb           13580 non-null object
Address          13580 non-null object
Rooms            13580 non-null int64
Type             13580 non-null object
Price            13580 non-null float64
Method           13580 non-null object
SellerG          13580 non-null object
Date             13580 non-null object
Distance         13580 non-null float64
Postcode         13580 non-null float64
Bedroom2         13580 non-null float64
Bathroom         13580 non-null float64
Car              13518 non-null float64
Landsize         13580 non-null float64
BuildingArea     7130 non-null float64
YearBuilt        8205 non-null float64
CouncilArea      12211 non-null object
Lattitude        13580 non-null float64
Longtitude       13580 non-null float64
Regionname       13580 non-null object
Propertycount    13580 non-null float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB


In [47]:
f = df['Address'].value_counts()
print(f[:5])

5 Margaret St    3
2 Bruce St       3
5 Charles St     3
53 William St    3
28 Blair St      3
Name: Address, dtype: int64


In [42]:
print(len(f))

13378


In [43]:
df['Address'].value_counts().sum()

13580

In [44]:
df['Address'].count()

13580

In [45]:
df['Address'].str.contains('5 Charles St').value_counts()   # this address comes 6 times in a column 

False    13574
True         6
Name: Address, dtype: int64

In [50]:
True + True   # Add two booean / logical values 

2

In [51]:
False + True 

1

In [52]:
False + False

0

In [53]:
False * True

0

In [54]:
'a'*2

'aa'

MAKE a list

In [55]:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50
areas = [hall, kit, liv, bed, bath]
areas

[11.25, 18.0, 20.0, 10.75, 9.5]

In [56]:
x = ["a", "b", "c", "d"]
print(x[1] + x[3])

bd


In [57]:
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
areas[-4:]    # last 4 elements

['bedroom', 10.75, 'bathroom', 9.5]

In [58]:
areas[-4:-1]

['bedroom', 10.75, 'bathroom']

In [59]:
liss = ['a','b','c','d']
liss[0:2] = ['p','q']
liss

['p', 'q', 'c', 'd']

In [60]:
# variable has the list reference address
liss = ['a','b','c','d']
print(liss)
k= liss   # copying the reference of the list
print(k)
k[2]='giga'
print(k)   # previous list will also be modified
print(liss)

['a', 'b', 'c', 'd']
['a', 'b', 'c', 'd']
['a', 'b', 'giga', 'd']
['a', 'b', 'giga', 'd']


In [62]:
liss = ['a','b','c','d']
k= liss[:]  # copying the elements of the list 'liss'
k[2]='giga'
print(k)   # previous list will not  be modified
print(liss)

['a', 'b', 'giga', 'd']
['a', 'b', 'c', 'd']


In [66]:
areas = ["hallway", 11.25, "kitchen", 18.0,
...         "chill zone", 20.0, "bedroom", 10.75,
...          "bathroom", 10.50, "poolhouse", 24.5,
...          "garage", 15.45]

del(areas[-3]); del(areas[-4])   # first it will remove '[-3]  = 24.5'  after that size/position will be changed # then remove '[-4] = 10.50'
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 'poolhouse', 'garage', 15.45]


In [67]:
areas = ["hallway", 11.25, "kitchen", 18.0,
...         "chill zone", 20.0, "bedroom", 10.75,
...          "bathroom", 10.50, "poolhouse", 24.5,
...          "garage", 15.45]  
 
del(areas[10]); del(areas[11])    # first remove [10]= 'poolhouse'   # then size/position/index is changed  after that remove [11]='garage'
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 24.5, 15.45]


#Round() function

In [6]:
round(1.48)  # give the output as 'floor()'

1

In [1]:
round(1.68)    # give the output as 'ceil()'

2

In [2]:
round(1.68,2)

1.68

In [3]:
round(1.68,3)

1.68

In [4]:
round(1.68,1)

1.7

#Others --


In [7]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second 

# Sort full in descending order: full_sorted
full_sorted_asc= sorted(full)   #bY DEFAULT ASCENDING ORDER

print(full_sorted_asc)

[9.5, 10.75, 11.25, 18.0, 20.0]


In [8]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second 

# Sort full in descending order: full_sorted
full_sorted_dsc = sorted(full,reverse=True) 
print(full_sorted_dsc)


[20.0, 18.0, 11.25, 10.75, 9.5]


In [12]:
strr = 'hello'
print(strr.capitalize())  # to make first letter capital alphabet

Hello


#NOTE: In PYTHON , everything is object , and each  object has methods , depending on type

such as : str() object has  replace() method , capitalize() method

In [15]:
strr.replace("e","E")

'hEllo'

In [17]:
strr

'hello'

In [16]:
strr.index('e')

1

In [1]:
place = "poolhouse"
place_up = place.upper()
print(place_up)
print(place.count('o'))

POOLHOUSE
3


In [2]:
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
print(areas.index(20.0))
print(areas.count(9.50))

2
1


In [4]:
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
areas.reverse()
areas

[9.5, 10.75, 20.0, 18.0, 11.25]

IN python 'Package' is a directory of python scripts . 

Each script is called 'Module.'

Each Module contains lot of function/Methods for calculate things faster 

In [5]:
import math
r = 0.43
C = 2*math.pi*r
A = math.pi*r**2
print(C)
print(A)

2.701769682087222
0.5808804816487527


#radians() funtion 

To convert an angle in degrees to an angle in radians, use the radians() function,

In [6]:
# radians(angle)
from math import radians
r = 192500
dist = r * radians(12)    # here 'phi' is the angle 
dist

40317.10572106901

umpy arrays cannot contain elements with different types. 

If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. This is known as **type coercion**.

In [8]:
import numpy as np
liss = ['a','1.25',True]
arr = np.array(liss)
arr     # all the elements of type 'U4'  # homogeneous

array(['a', '1.25', 'True'], dtype='<U4')

In [9]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [12]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]
print(type(baseball))
# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

print(np_baseball)
print(type(np_baseball))

<class 'list'>
[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]
<class 'numpy.ndarray'>


In [13]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
var1= np_mat * 2
print(var1)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [14]:
var2 = np_mat + np.array([10, 10])
print(var2)


[[11 12]
 [13 14]
 [15 16]]


In [15]:
var3 = np_mat + np_mat
print(var3)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [19]:
conversion = np.array([0.0254, 0.0453592, 1])
conversion

array([0.0254   , 0.0453592, 1.       ])

In [21]:
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]]) 
cov = np.array([2,4])    # for cloumn_1  & column_2

print(np_mat*cov)

[[ 2  8]
 [ 6 16]
 [10 24]]


#Numpy array

In [22]:
import numpy as np
x = [1, 4, 8, 10, 12]
print(np.mean(x))
print(np.median(x))

7.0
8.0


In [0]:
# np.corrcoef() funtion
# correlation method
