<a href="https://colab.research.google.com/github/priyanshgupta1998/All_codes/blob/master/numpy0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
create_array = np.array([[7,8,9],[4,5,6]])

In [55]:
print(create_array)

[[7 8 9]
 [4 5 6]]


In [59]:
r_array = create_array.reshape(1,6)
print(r_array)

[[7 8 9 4 5 6]]


In [60]:
r_array = create_array.reshape(6,1)
print(r_array)

[[7]
 [8]
 [9]
 [4]
 [5]
 [6]]


In [61]:
zero_mat = np.zeros([2,4])
print(zero_mat)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [62]:
zero_mat = np.zeros([2,4],dtype =int)
print(zero_mat)

[[0 0 0 0]
 [0 0 0 0]]


In [63]:
one_mat = np.ones([2,4])
print(one_mat)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [64]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [66]:
arr2 = np.append(arr,[4,6])
print(arr2)

[1 2 3 4 6]


In [67]:
arr3 = np.delete(arr , 1 )
print(arr3)

[1 3]


In [72]:
arr4 = np.concatenate((arr , np.array([9,4])),axis = 0)
print(arr4)

[1 2 3 9 4]


#Now look  at some different properties of numpy

In [76]:
get_extended_np_array = np.arange(20)
print(get_extended_np_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [77]:
print(get_extended_np_array[4:8])

[4 5 6 7]


In [81]:
a2 = np.array([[1,2,3],[3,4,5],[4,5,6],[7,5,3]])
print(a2[2:])

[[4 5 6]
 [7 5 3]]


In [82]:
print(a2[:3])  #excluding 3 

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [80]:
print(a2[:4])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
