<a href="https://colab.research.google.com/github/priyanshgupta1998/All_codes/blob/master/pandas_normalization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



---

---



---



---





---



---



---



In [0]:
import numpy as np 
s = pd.DataFrame([49,48,47,46,45, 1, 2, 3, 4, 5] )
s['1'] = 
s
import random
p=[]
for i in range(10):
    p.append(random.randint(0,100))
s['4'] = p
s.iloc[: , 2:4]

In [0]:
import numpy as np
from sklearn.preprocessing import normalize

 # Values as floats or normalize raises a type error
# 2D Matrix of 5 x 4 size
X1 = np.array([
              [1., 0., 0., 4., 15.],
              [1., 0., 0., 3., 7.],
              [0., 1., 0., 5., 9.],
              [0., 0., 1., 4., 15.],
                      ])


X1[:, [3,4]]    # last two columns

array([[ 4., 15.],
       [ 3.,  7.],
       [ 5.,  9.],
       [ 4., 15.]])

In [0]:
#Normalize the last two columns and assign to a new numpy array, X2.
X2 = normalize(X1[:, [3,4]], axis=0) #axis=0 for column-wise
X2

array([[0.49236596, 0.6228411 ],
       [0.36927447, 0.29065918],
       [0.61545745, 0.37370466],
       [0.49236596, 0.6228411 ]])

In [0]:
#Now concatenate X1 and X2 for your desired output.
np.concatenate(( X1[:,[0,1,2]], X2), axis=1)

array([[1.        , 0.        , 0.        , 0.49236596, 0.6228411 ],
       [1.        , 0.        , 0.        , 0.36927447, 0.29065918],
       [0.        , 1.        , 0.        , 0.61545745, 0.37370466],
       [0.        , 0.        , 1.        , 0.49236596, 0.6228411 ]])