<a href="https://colab.research.google.com/github/priyanshgupta1998/All_codes/blob/master/pract2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn.feature_extraction import DictVectorizer


In [2]:
v = DictVectorizer(sparse=False)
D = [{'foo': 1, 'bar': 2}, {'foo': 3, 'baz': 1}]
D

[{'bar': 2, 'foo': 1}, {'baz': 1, 'foo': 3}]

In [3]:
X = v.fit_transform(D)
X


array([[2., 0., 1.],
       [0., 1., 3.]])

In [4]:
type(X)

numpy.ndarray

In [5]:
v.inverse_transform(X) ==[{'bar': 2.0, 'foo': 1.0}, {'baz': 1.0, 'foo': 3.0}]

True

In [6]:
 v.transform({'foo': 4, 'unseen_feature': 3})

array([[0., 0., 4.]])

In [13]:
v1 = DictVectorizer(sparse=False)
D1 = [{'foo': 1, 'bar': 5 , 'foo': 4}, {'foo': 3, 'baz': 1 , 'foo': 4} , {'sam': 4, 'john': 5 , 'foo': 2}]
D1

[{'bar': 5, 'foo': 4}, {'baz': 1, 'foo': 4}, {'foo': 2, 'john': 5, 'sam': 4}]

In [14]:
X1 = v1.fit_transform(D1)
X1

array([[5., 0., 4., 0., 0.],
       [0., 1., 4., 0., 0.],
       [0., 0., 2., 5., 4.]])