<a href="https://colab.research.google.com/github/priyanshgupta1998/All_codes/blob/master/Reshape_with_numpy0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Reshape funtiuon with Numpy

**convert One dimentional array into two-dimentional array or multi-dimentional array , we use a funtion called -->reshape**

By using 'reshape' function we create a new view of the existing array but with different dimensions



```
Reshape funcion takes 3 arguments 
1.) No. of Blocks of the data ,which we want to create
2.) No. of Rows , you want to have
3.) NO. of columns ,which we want in each block of the data
```





```
But if we don't specify , then it will create 1 block of the data (By default)
```



Let's create one dimentional array

In [0]:
import numpy as np

In [60]:
arr1 = np.arange(0,12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Now we will create one block of data , which has 3 rows and 4 columns

In [61]:
arr2 = arr1.reshape(3,4)  # convert arr1 to two-dimensinal array of 3 rows and 4 columns
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Now we will create two blocks of data , where each of block has 2 rows and 3 columns

In [54]:
arr3 = arr1.reshape(2,2,3)    # 3-dimentional array
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

Now we will create three blocks of data , where each of block has 2 rows and 2 columns

In [55]:
arr4 = arr1.reshape(3,2,2)   #multidimentonal 3d array
arr4 

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])



```
Whitout creating an one dimentional array we can directly create two dimentional array by using 'reshape' function with arange function.
```



In [68]:
arr4.shape

(3, 2, 2)

In [56]:
arr5 = np.arange(0,9).reshape(3,3)  #2dimentional array 
arr5 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#Shape Funtion



```
Shape funtion is useful we want to change the dimensions of the existing array without creating a new array . So we can modify the dimension of the existing array.
```



In [62]:
arr1.shape   # one dimensional with 1 row and 12 columns

(12,)

In [63]:
arr1.shape=[3,4]
arr1.shape

(3, 4)

In [64]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#Another Example

In [67]:
a = np.array([1,2,3]) #one dimensional array 
a

array([1, 2, 3])

In [66]:
np.shape(a)

(3,)

In [72]:
a3d = np.array([[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4]]])
a3d

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [73]:
a3d.shape  #2 blocks and each of blocks has 2 rows and 4 columns

(2, 2, 4)

In [74]:
np.shape(a3d)

(2, 2, 4)

In [75]:
k = np.array([1,2,3,4])  #1-d array
k

array([1, 2, 3, 4])

In [76]:
b = np.reshape(k,(2,2))  # 2-d array
b

array([[1, 2],
       [3, 4]])

In [77]:
b.shape = [4,1]  #2-d array with 14 rows and 1 column
b

array([[1],
       [2],
       [3],
       [4]])

In [80]:
b = k.reshape((2,2))
b

array([[1, 2],
       [3, 4]])